name: 同步源码 

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'GitHub\Auto-Update-Openwrt'
        required: true
        default: '同步源码'
  
  # 点赞☆Star触发编译
  watch:
     types: [started]
  
  schedule:
    # - cron: 30 6,18 * * *
    - cron: 30 18 * * *
env: 
  SCKEY: ${{ secrets.WEIXIN_SCKEY }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu-20.04

    name: Update ${{matrix.target}}
    strategy:
      fail-fast: false
      matrix:
        target: [18.06,19.07,lede-openwrt,Lienol-openwrt,Lienol-openwrt21.02]  #[main,18.06,19.07,lede-openwrt,Lienol-openwrt]  

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install git subversion git-core wget
        sudo timedatectl set-timezone "$TZ"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ${{matrix.target}}.sh
        git clone -b ${{matrix.target}} https://github.com/authon/authon-openwrt-hub.git ${{matrix.target}}
        cd ${{matrix.target}}
        rm -Rf *
        git rm --cache *
        $GITHUB_WORKSPACE/${{matrix.target}}.sh

    - name: Upload
      env: 
        GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
      run: |
        [ -e $GITHUB_WORKSPACE/LICENSE ] && cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/${{matrix.target}}
        [ -e $GITHUB_WORKSPACE/README/${{matrix.target}}/README.md ] && cp $GITHUB_WORKSPACE/README/${{matrix.target}}/README.md $GITHUB_WORKSPACE/${{matrix.target}}
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "同步源码于$(TZ='Asia/Shanghai' date +%Y年%m月%d号-%H点%M分)"
        git push --quiet "https://${{ secrets.UPDATE }}@github.com/authon/authon-openwrt-hub.git" HEAD:${{matrix.target}}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 90
        keep_minimum_runs: 30
